### ISSUE TITLE
Spec failures

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-gb#39]
https://github.com/relaton/relaton-gb/runs/4515363689?check_suite_focus=true

Due to Net::Timeout on various platforms.

**Comment by andrew2net** [comment]
@ronaldtse The http://www.std.gov.cn unavailable from my location:
```
$ host www.std.gov.cn
Host www.std.gov.cn not found: 2(SERVFAIL)
```

**Comment by andrew2net** [comment]
@ronaldtse VCR cassettes are updated if more than a week passed since the last update. Usually, we run tests locally before pushing the code to GitHub, so GHA doesn't fetch data from sites, but uses VCR cassettes. In this case, the tests were running on GHA and 7 days were passed so the VCR tries to update the cassette. I think because many containers make requests from one location the source server blocks some of them. I've updated the VCR cassettes locally the tests pass now.
